
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Natasya
 */
public class ProgramGame extends javax.swing.JFrame {
    String Sp1, Sp2;
    String pp1,pp2;
    /**
     * Creates new form ProgramGame
     */
    public ProgramGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Judul = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bHasil = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        p2 = new javax.swing.JLabel();
        cbP2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        p1 = new javax.swing.JLabel();
        cbP1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Judul.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul.setText("Program Permainan Gunting Batu Kertas");
        getContentPane().add(Judul, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 40));

        bHasil.setText("Hasil");
        bHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHasilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(bHasil)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bHasil)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 200));

        p2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        p2.setText("Player 2");

        cbP2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cbP2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Skill", "Gunting", "Batu", "Kertas" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(cbP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(p2)
                        .addGap(68, 68, 68))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(p2)
                .addGap(40, 40, 40)
                .addComponent(cbP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 200));

        p1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        p1.setForeground(new java.awt.Color(255, 255, 255));
        p1.setText("Player 1");

        cbP1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cbP1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Skill", "Gunting", "Batu", "Kertas" }));
        cbP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(p1)
                .addGap(42, 42, 42)
                .addComponent(cbP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHasilActionPerformed
        Sp1 = (String) cbP1.getSelectedItem();
        Sp2 = (String) cbP2.getSelectedItem();
        
        switch (Sp1){
            case "Gunting" :
                pp1 = "Gunting";
                break;
            case "Kertas" :
                pp1 = "Kertas";
                break;
            case "Batu" :
                pp1 = "Batu";
                break;
        }
        
        switch (Sp2){
            case "Gunting" :
                pp2 = "Gunting";
                break;
            case "Kertas" :
                pp2 = "Kertas";
                break;
            case "Batu" :
                pp2 = "Batu";
                break;
        }
        
        if ((pp1 == "Gunting")&&(pp2 == "Kertas")){
            JOptionPane.showMessageDialog(this, "Player 1 Menang!");
        } else if ((pp1 == "Kertas")&& (pp2 == "Batu")){
            JOptionPane.showMessageDialog(this, "Player 1 Menang!");
        } else if ((pp1 == "Batu")&& (pp2 == "Gunting")){
            JOptionPane.showMessageDialog(this, "Player 1 Menang!");
        } else if ((pp1 == "Gunting")&& (pp2 == "Gunting")){
            JOptionPane.showMessageDialog(this, "Hasil Imbang!");
        } else if ((pp1 == "Batu")&& (pp2 == "Batu")){
            JOptionPane.showMessageDialog(this, "Hasil Imbang!");
        } else if ((pp1 == "Batu")&& (pp2 == "Batu")){
            JOptionPane.showMessageDialog(this, "Hasil Imbang!");
        } else if ((pp2 == "Kertas")&& (pp1 == "Batu")){
            JOptionPane.showMessageDialog(this, "Player 1 Menang!");
        } else if ((pp2 == "Batu")&& (pp1 == "Gunting")){
            JOptionPane.showMessageDialog(this, "Player 1 Menang!");
        }else if ((pp2 == "Gunting")&& (pp1 == "Kertas")){
            JOptionPane.showMessageDialog(this, "Player 1 Menang!");
        }
        
    }//GEN-LAST:event_bHasilActionPerformed

    private void cbP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbP1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JButton bHasil;
    private javax.swing.JComboBox<String> cbP1;
    private javax.swing.JComboBox<String> cbP2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    // End of variables declaration//GEN-END:variables
}
