import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Natasya
 */
public class PendaftaranUKM extends javax.swing.JFrame {
    String pProdi = "";
    String pAngkatan = "";
    String pAgama = "";
    String mprodi,mangkatan,magama;
    public PendaftaranUKM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        judul2 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        uNama = new javax.swing.JTextField();
        nim = new javax.swing.JLabel();
        prodi = new javax.swing.JLabel();
        angkatan = new javax.swing.JLabel();
        jeniskelamin = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        uLaki = new javax.swing.JRadioButton();
        uPerempuan = new javax.swing.JRadioButton();
        uProdi = new javax.swing.JComboBox<>();
        uNim = new javax.swing.JTextField();
        uAngkatan = new javax.swing.JComboBox<>();
        agama = new javax.swing.JLabel();
        uAlamat = new javax.swing.JTextField();
        uAgama = new javax.swing.JComboBox<>();
        judul = new javax.swing.JLabel();
        bSimpan = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        judul2.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        judul2.setForeground(new java.awt.Color(255, 255, 255));
        judul2.setText("UKMFT-TOFATEK");
        getContentPane().add(judul2);
        judul2.setBounds(140, 70, 310, 48);

        nama.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setText("Nama Lengkap");
        getContentPane().add(nama);
        nama.setBounds(110, 140, 140, 18);

        uNama.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        uNama.setToolTipText("Kolom ini wajib diisi");
        uNama.setName(""); // NOI18N
        uNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uNamaActionPerformed(evt);
            }
        });
        getContentPane().add(uNama);
        uNama.setBounds(270, 130, 199, 30);
        uNama.getAccessibleContext().setAccessibleName("");
        uNama.getAccessibleContext().setAccessibleDescription("");

        nim.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        nim.setForeground(new java.awt.Color(255, 255, 255));
        nim.setText("NIM");
        getContentPane().add(nim);
        nim.setBounds(110, 180, 50, 18);

        prodi.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        prodi.setForeground(new java.awt.Color(255, 255, 255));
        prodi.setText("Prodi");
        getContentPane().add(prodi);
        prodi.setBounds(110, 220, 50, 18);

        angkatan.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        angkatan.setForeground(new java.awt.Color(255, 255, 255));
        angkatan.setText("Angkatan");
        getContentPane().add(angkatan);
        angkatan.setBounds(110, 250, 80, 18);

        jeniskelamin.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jeniskelamin.setForeground(new java.awt.Color(255, 255, 255));
        jeniskelamin.setText("Jenis Kelamin");
        getContentPane().add(jeniskelamin);
        jeniskelamin.setBounds(110, 290, 110, 18);

        alamat.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        alamat.setForeground(new java.awt.Color(255, 255, 255));
        alamat.setText("Alamat");
        getContentPane().add(alamat);
        alamat.setBounds(110, 360, 54, 18);

        buttonGroup1.add(uLaki);
        uLaki.setText("Laki-Laki");
        uLaki.setToolTipText("");
        getContentPane().add(uLaki);
        uLaki.setBounds(270, 290, 98, 21);

        buttonGroup1.add(uPerempuan);
        uPerempuan.setText("Perempuan");
        getContentPane().add(uPerempuan);
        uPerempuan.setBounds(390, 290, 98, 21);

        uProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan Prodi", "Sistem Informasi", "Teknik Informatika", "Teknik Industri", "Teknik Elektro", "Teknik Mekatro", "Teknik Mesin" }));
        uProdi.setToolTipText("Silahkan memilih prodi anda");
        uProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uProdiActionPerformed(evt);
            }
        });
        getContentPane().add(uProdi);
        uProdi.setBounds(270, 210, 199, 30);

        uNim.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        uNim.setToolTipText("Kolom ini wajib diisi");
        getContentPane().add(uNim);
        uNim.setBounds(270, 170, 199, 30);

        uAngkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan Angkatan", "2020", "2021", "2022", "2023" }));
        uAngkatan.setToolTipText("Silahkan memilih angkatan");
        uAngkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uAngkatanActionPerformed(evt);
            }
        });
        getContentPane().add(uAngkatan);
        uAngkatan.setBounds(270, 250, 199, 30);

        agama.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        agama.setForeground(new java.awt.Color(255, 255, 255));
        agama.setText("Agama");
        getContentPane().add(agama);
        agama.setBounds(110, 320, 60, 18);

        uAlamat.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        uAlamat.setToolTipText("Kolom ini wajib diisi");
        getContentPane().add(uAlamat);
        uAlamat.setBounds(270, 360, 200, 30);

        uAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan Agama", "Islam", "Kristen", "Hindu", "Buddha" }));
        uAgama.setToolTipText("Silahkan pilih agama");
        uAgama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uAgamaActionPerformed(evt);
            }
        });
        getContentPane().add(uAgama);
        uAgama.setBounds(270, 320, 200, 30);

        judul.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setText("FORMULIR PENDAFTARAN");
        getContentPane().add(judul);
        judul.setBounds(140, 30, 310, 50);

        bSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bSimpan);
        bSimpan.setBounds(270, 420, 100, 27);

        bReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });
        getContentPane().add(bReset);
        bReset.setBounds(380, 420, 90, 27);

        bKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bKeluar);
        bKeluar.setBounds(556, 10, 30, 27);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tofatek.png"))); // NOI18N
        bg.setText("jLabel10");
        getContentPane().add(bg);
        bg.setBounds(0, 0, 600, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uNamaActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        String nama = uNama.getText(); 
        String nim = uNim.getText();
        String alamat = uAlamat.getText();
        String jk;
        
        if(uLaki.isSelected()){
            jk = "Laki-laki";
        }else{
            jk = "Perempuan";
        }
        
        JOptionPane.showMessageDialog(this, "Nama: " + nama 
                + "\nNim: " + nim 
                + "\nProdi: " + mprodi 
                + "\nAngkatan: " + mangkatan 
                + "\nJenis Kelamin: " + jk 
                + "\nAgama: " + magama 
                + "\nAlamat: " + alamat );
    }//GEN-LAST:event_bSimpanActionPerformed

    private void uProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uProdiActionPerformed
        pProdi = (String) uProdi.getSelectedItem();
        switch (pProdi){
            case "Pilihan Prodi" : 
                mprodi = "-";
                break;
            case "Sistem Informasi" :
                mprodi = "Sistem Informasi";
                break;
            case "Teknik Informatika" :
                mprodi = "Teknik Informatika";
                break;
            case "Teknik Industri" :
                mprodi = "Teknik Industri";
                break;
            case "Teknik Elektro" :
                mprodi = "Teknik Elektro";
                break;
            case "Teknik Mesin" :
                mprodi = "Teknik Mesin";
                break;
            case "Teknik Mekatro" :
                mprodi = "Teknik Mekatro";
                break;
        }
    }//GEN-LAST:event_uProdiActionPerformed

    private void uAngkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uAngkatanActionPerformed
        pAngkatan = (String) uAngkatan.getSelectedItem();
        switch (pAngkatan){
            case "Pilihan Angkatan" : 
                mangkatan = "-";
                break;
            case "2020" :
                mangkatan = "2020";
                break;
            case "2021" :
                mangkatan = "2021";
                break;
            case "2022" :
                mangkatan = "2022";
                break;
            case "2023" :
                mangkatan = "2023";
                break;
        }
    }//GEN-LAST:event_uAngkatanActionPerformed

    private void uAgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uAgamaActionPerformed
        pAgama = (String) uAgama.getSelectedItem();
        switch (pAgama){
            case "Pilihan Agama" : 
                magama = "-";
                break;
            case "Islam" :
                magama = "Islam";
                break;
            case "Kristen" :
                magama = "Kristen";
                break;
            case "Buddha" :
                magama = "Buddha";
                break;
            case "Hindu" :
                magama = "Hindu";
                break;
        }
    }//GEN-LAST:event_uAgamaActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        uNama.setText("");
        uNim.setText("");
        uAlamat.setText("");
        uAngkatan.setSelectedIndex(0);
        uAgama.setSelectedIndex(0);
        uProdi.setSelectedIndex(0);

        
    }//GEN-LAST:event_bResetActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendaftaranUKM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendaftaranUKM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendaftaranUKM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendaftaranUKM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendaftaranUKM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agama;
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel angkatan;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bSimpan;
    private javax.swing.JLabel bg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jeniskelamin;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nim;
    private javax.swing.JLabel prodi;
    private javax.swing.JComboBox<String> uAgama;
    private javax.swing.JTextField uAlamat;
    private javax.swing.JComboBox<String> uAngkatan;
    private javax.swing.JRadioButton uLaki;
    private javax.swing.JTextField uNama;
    private javax.swing.JTextField uNim;
    private javax.swing.JRadioButton uPerempuan;
    private javax.swing.JComboBox<String> uProdi;
    // End of variables declaration//GEN-END:variables
}
