import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Natasya
 */
public class TimerSederhana extends javax.swing.JFrame {
    Timer waktu;
    int hitung;
    
    public TimerSederhana() {
        initComponents();
        waktu = new Timer (1000, new ActionListener(){
            public void actionPerformed(ActionEvent e) {
                uAngka.setText("" + hitung);
                hitung--;
                if(hitung==0){
                    waktu.stop();
                    JOptionPane.showMessageDialog(null, "Waktu telah selesai");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        b30 = new javax.swing.JButton();
        b60 = new javax.swing.JButton();
        bManual = new javax.swing.JButton();
        uAngka = new javax.swing.JTextField();
        bReset = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Aplikasi Timer Sederhana");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(82, 11, 292, 32);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pilihan Durasi");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 60, 111, 24);

        b30.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        b30.setText("30 detik");
        b30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b30ActionPerformed(evt);
            }
        });
        getContentPane().add(b30);
        b30.setBounds(57, 113, 80, 30);

        b60.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        b60.setText("60 detik");
        b60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b60ActionPerformed(evt);
            }
        });
        getContentPane().add(b60);
        b60.setBounds(294, 113, 80, 30);

        bManual.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bManual.setText("Lainnya");
        bManual.setToolTipText("");
        bManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bManualActionPerformed(evt);
            }
        });
        getContentPane().add(bManual);
        bManual.setBounds(180, 150, 80, 30);

        uAngka.setBackground(new java.awt.Color(51, 255, 51));
        uAngka.setFont(new java.awt.Font("hooge 05_55", 1, 18)); // NOI18N
        uAngka.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        uAngka.setToolTipText("Isi dengan durasi yang anda inginkan");
        getContentPane().add(uAngka);
        uAngka.setBounds(180, 300, 96, 89);

        bReset.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bReset.setText("Reset");
        bReset.setToolTipText("Klik untuk melakukan perhitungan ulang");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });
        getContentPane().add(bReset);
        bReset.setBounds(240, 410, 72, 26);

        bKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bKeluar);
        bKeluar.setBounds(403, 16, 26, 27);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TIME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 280, 37, 19);

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Stop");
        jButton1.setToolTipText("Klik untuk menghentikan perhitungan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 410, 72, 26);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cara memasukkan angka secara manual :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 210, 220, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("1. Masukkan angka pada kotak dibawah");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 230, 210, 16);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("2. Klik tombol \"Lainnya\"");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 250, 140, 16);

        bg.setBackground(new java.awt.Color(255, 153, 0));
        bg.setForeground(new java.awt.Color(255, 153, 0));
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 440, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b30ActionPerformed
        hitung = 30;
        waktu.start();
    }//GEN-LAST:event_b30ActionPerformed

    private void bManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bManualActionPerformed
        hitung = Integer.parseInt(uAngka.getText());
        waktu.start();
    }//GEN-LAST:event_bManualActionPerformed

    private void b60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b60ActionPerformed
        hitung = 60;
        waktu.start();
    }//GEN-LAST:event_b60ActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bKeluarActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        uAngka.setText("");
        waktu.stop();
    }//GEN-LAST:event_bResetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        waktu.stop();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimerSederhana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b30;
    private javax.swing.JButton b60;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bManual;
    private javax.swing.JButton bReset;
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField uAngka;
    // End of variables declaration//GEN-END:variables
}
