/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package koneksi;
//dikasi pemberitahuan kalo nominal ga cukup
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import static koneksi.koneksi.koneksiDB;

/**
 *
 * @author Natasya
 */
public class Main extends javax.swing.JFrame {
    int jumlah;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        dropdown();
        tdata();

        bTambah.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                jumlah++;
                lJumlah.setText(Integer.toString(jumlah));
            }
        });

        bKurang.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (jumlah > 0) {
                    jumlah--;
                    lJumlah.setText(Integer.toString(jumlah));
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jtData = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        pInfo = new javax.swing.JPanel();
        pBar = new javax.swing.JPanel();
        total1 = new javax.swing.JLabel();
        lTotal = new javax.swing.JLabel();
        batas1 = new javax.swing.JLabel();
        nama_kasirnya = new javax.swing.JLabel();
        tanggalnya = new javax.swing.JLabel();
        cash = new javax.swing.JLabel();
        batas2 = new javax.swing.JLabel();
        namakasir = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        metodepembayaran = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Jumlah = new javax.swing.JLabel();
        lKode = new javax.swing.JTextField();
        lHarga = new javax.swing.JTextField();
        lJumlah = new javax.swing.JLabel();
        bTambah = new javax.swing.JButton();
        bKurang = new javax.swing.JButton();
        cbPilihan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPemesanan = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        Nominal = new javax.swing.JLabel();
        Kembalian = new javax.swing.JLabel();
        uNominal = new javax.swing.JTextField();
        uKembalian = new javax.swing.JTextField();
        bBayar = new javax.swing.JButton();
        bHitung = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        pFooter = new javax.swing.JPanel();
        bSimpan = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pInfo1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbRiwayat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setOpaque(true);
        jInternalFrame1.setVisible(true);

        pInfo.setBackground(new java.awt.Color(0, 0, 0));
        pInfo.setPreferredSize(new java.awt.Dimension(793, 130));

        pBar.setBackground(new java.awt.Color(0, 0, 0));
        pBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        total1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        total1.setForeground(new java.awt.Color(0, 153, 255));
        total1.setText("TOTAL");

        lTotal.setBackground(new java.awt.Color(255, 255, 255));
        lTotal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lTotal.setForeground(new java.awt.Color(255, 255, 255));
        lTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lTotal.setText("Rp. 0");
        lTotal.setToolTipText("");

        javax.swing.GroupLayout pBarLayout = new javax.swing.GroupLayout(pBar);
        pBar.setLayout(pBarLayout);
        pBarLayout.setHorizontalGroup(
            pBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(total1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pBarLayout.setVerticalGroup(
            pBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBarLayout.createSequentialGroup()
                .addGroup(pBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(total1))
                    .addGroup(pBarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lTotal)))
                .addContainerGap(218, Short.MAX_VALUE))
        );

        batas1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        batas1.setForeground(new java.awt.Color(255, 255, 255));
        batas1.setText("|");

        nama_kasirnya.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nama_kasirnya.setForeground(new java.awt.Color(255, 255, 255));
        nama_kasirnya.setText("Natasya");

        tanggalnya.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tanggalnya.setForeground(new java.awt.Color(255, 255, 255));
        tanggalnya.setText("24 Nov 2023");

        cash.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cash.setForeground(new java.awt.Color(255, 255, 255));
        cash.setText("CASH");

        batas2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        batas2.setForeground(new java.awt.Color(255, 255, 255));
        batas2.setText("|");

        namakasir.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        namakasir.setForeground(new java.awt.Color(255, 255, 255));
        namakasir.setText("Nama Kasir :");

        tanggal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tanggal.setForeground(new java.awt.Color(255, 255, 255));
        tanggal.setText("Tanggal :");

        metodepembayaran.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        metodepembayaran.setForeground(new java.awt.Color(255, 255, 255));
        metodepembayaran.setText("Metode Pembayaran :");

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        logo.setText("jLabel12");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/koneksi/SstShop Logoo.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(logo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pInfoLayout = new javax.swing.GroupLayout(pInfo);
        pInfo.setLayout(pInfoLayout);
        pInfoLayout.setHorizontalGroup(
            pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 445, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pInfoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cash, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(metodepembayaran, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(batas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tanggalnya)
                            .addComponent(tanggal))
                        .addGap(12, 12, 12)
                        .addComponent(batas2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namakasir)
                            .addComponent(nama_kasirnya))
                        .addGap(23, 23, 23))))
        );
        pInfoLayout.setVerticalGroup(
            pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfoLayout.createSequentialGroup()
                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pInfoLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(208, 208, 208))
                    .addGroup(pInfoLayout.createSequentialGroup()
                        .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pInfoLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(metodepembayaran, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tanggal)
                                        .addComponent(namakasir)))
                                .addGap(6, 6, 6)
                                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cash, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nama_kasirnya)
                                        .addComponent(tanggalnya))))
                            .addComponent(batas2)
                            .addComponent(batas1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nama Item");

        jLabel2.setText("Harga");

        jLabel3.setText("Kode Item");

        Jumlah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jumlah.setText("Jumlah");

        lKode.setEditable(false);

        lHarga.setEditable(false);

        lJumlah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lJumlah.setText("0");

        bTambah.setText("+");

        bKurang.setText("-");

        cbPilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Item", "Mie Goreng", "Mie Soto", "Mie Kari", "Mie Rendang" }));
        cbPilihan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPilihanItemStateChanged(evt);
            }
        });

        tbPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Harga", "Jumlah", "Nominal", "Kembalian"
            }
        ));
        tbPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPemesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPemesanan);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        Nominal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Nominal.setText("NOMINAL:");

        Kembalian.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Kembalian.setForeground(new java.awt.Color(0, 153, 255));
        Kembalian.setText("KEMBALIAN:");

        uNominal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        uNominal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        uNominal.setText("Rp. 0");

        uKembalian.setEditable(false);
        uKembalian.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        uKembalian.setForeground(new java.awt.Color(0, 153, 255));
        uKembalian.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        uKembalian.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Kembalian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uKembalian))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(Nominal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uNominal, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nominal)
                    .addComponent(uNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kembalian)
                    .addComponent(uKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bBayar.setBackground(new java.awt.Color(0, 153, 255));
        bBayar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bBayar.setForeground(new java.awt.Color(255, 255, 255));
        bBayar.setText("Bayar");
        bBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBayarActionPerformed(evt);
            }
        });

        bHitung.setText("Hitung");
        bHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbPilihan, 0, 146, Short.MAX_VALUE)
                                    .addComponent(lKode, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(lHarga))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(bKurang)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bTambah)))
                                .addGap(18, 18, 18)))
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(Jumlah)
                                    .addComponent(cbPilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(lJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bKurang)
                                    .addComponent(bTambah))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(bHitung)))
                            .addComponent(bBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pFooter.setBackground(new java.awt.Color(255, 255, 255));
        pFooter.setPreferredSize(new java.awt.Dimension(806, 90));

        bSimpan.setBackground(new java.awt.Color(0, 153, 255));
        bSimpan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bSimpan.setForeground(new java.awt.Color(255, 255, 255));
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bHapus.setBackground(new java.awt.Color(0, 153, 255));
        bHapus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bReset.setBackground(new java.awt.Color(0, 153, 255));
        bReset.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bReset.setForeground(new java.awt.Color(255, 255, 255));
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        bEdit.setBackground(new java.awt.Color(0, 153, 255));
        bEdit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bEdit.setForeground(new java.awt.Color(255, 255, 255));
        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pFooterLayout = new javax.swing.GroupLayout(pFooter);
        pFooter.setLayout(pFooterLayout);
        pFooterLayout.setHorizontalGroup(
            pFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFooterLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(bEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        pFooterLayout.setVerticalGroup(
            pFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(pFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addComponent(pFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtData.addTab("Kasir", jPanel2);

        pInfo1.setBackground(new java.awt.Color(0, 0, 0));
        pInfo1.setPreferredSize(new java.awt.Dimension(793, 130));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/koneksi/SstShop Logoo.png"))); // NOI18N
        jLabel5.setText("jLabel4");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/koneksi/SstShop Logoo.png"))); // NOI18N
        jLabel7.setText("jLabel4");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pInfo1Layout = new javax.swing.GroupLayout(pInfo1);
        pInfo1.setLayout(pInfo1Layout);
        pInfo1Layout.setHorizontalGroup(
            pInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfo1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        pInfo1Layout.setVerticalGroup(
            pInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfo1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tbRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Harga", "Jumlah", "Nominal", "Kembalian"
            }
        ));
        tbRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRiwayatMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbRiwayat);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jtData.addTab("Riwayat Penjualan", jPanel1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtData)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtData)
        );

        getContentPane().add(jInternalFrame1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbRiwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRiwayatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRiwayatMouseClicked

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        try {
            java.sql.Connection conn = koneksiDB();
            Statement st = conn.createStatement();
            st.executeUpdate("UPDATE data_jual SET nama_item ='" + cbPilihan.getSelectedItem()
                    + "', harga='" + lHarga.getText() + "', jumlah='" + lJumlah.getText()
                    + "', total='" + lTotal.getText() + "', nominal='" + uNominal.getText()
                    + "', kembalian='" + uKembalian.getText() + "' WHERE kode_item='" + lKode.getText() + "'");
            st.close();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah");
            tdata();
        } catch (Exception t) {
            System.out.println(t.getMessage());
        }
    }//GEN-LAST:event_bEditActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        cbPilihan.setSelectedIndex(0);
        lKode.setText("");
        lHarga.setText("");
        lJumlah.setText("0");
        lTotal.setText("");
        uNominal.setText("");
        uKembalian.setText("");
    }//GEN-LAST:event_bResetActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        try {
            java.sql.Connection conn = koneksiDB();
            Statement st = conn.createStatement();
            st.executeUpdate("DELETE FROM data_jual WHERE kode_item='" + lKode.getText() + "' ");
            st.close();
            JOptionPane.showMessageDialog(this, "data berhasil dihapus");
            tdata();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "data gagal dihapus" + e.getMessage());
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        String pilih = (String) cbPilihan.getSelectedItem();
        switch (pilih) {
            case "Mie Goreng":
                break;
            case "Mie Soto":
                break;
            case "Mie Kari":
                break;
            case "Mie Rendang":
                break;
        }

        try {
            java.sql.Connection conn = koneksiDB();
            Statement st = conn.createStatement();
            st.executeUpdate("INSERT INTO data_jual VALUES('" + lKode.getText()
                    + "','" + pilih + "','" + lHarga.getText() + "','" + lJumlah.getText()
                    + "','" + lTotal.getText() + "','" + uNominal.getText() + "','" + uKembalian.getText()
                    + "')");
            st.close();
            tdata();
            JOptionPane.showMessageDialog(this, "data berhasil disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "data gagal disimpan" + e.getMessage());
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        int jumlah = Integer.parseInt(lJumlah.getText());
        int harga = Integer.parseInt(lHarga.getText());
        int bayar = harga * jumlah;

        lTotal.setText(Integer.toString(bayar));
    }//GEN-LAST:event_bHitungActionPerformed

    private void bBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBayarActionPerformed
        int total = Integer.parseInt(lTotal.getText());
        int cash = Integer.parseInt(uNominal.getText());
        int bayar = cash - total;
        if (cash < total){
            JOptionPane.showMessageDialog(this, "Maaf nominal pembayaran anda kurang");
            uNominal.setText("0");
        }else{
        uKembalian.setText(Integer.toString(bayar));
        }
    }//GEN-LAST:event_bBayarActionPerformed

    private void tbPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPemesananMouseClicked
        int row = tbPemesanan.rowAtPoint(evt.getPoint());

        String kode = tbPemesanan.getValueAt(row, 0).toString();
        lKode.setText(kode);
        String pilihan = tbPemesanan.getValueAt(row, 1).toString();
        cbPilihan.setSelectedItem(pilihan);
        String harga = tbPemesanan.getValueAt(row, 2).toString();
        lHarga.setText(harga);
        String jumlah = tbPemesanan.getValueAt(row, 3).toString();
        lJumlah.setText(jumlah);
        String total = tbPemesanan.getValueAt(row, 4).toString();
        lTotal.setText(total);
        String nominal = tbPemesanan.getValueAt(row, 5).toString();
        uNominal.setText(nominal);
        String kembalian = tbPemesanan.getValueAt(row, 6).toString();
        uKembalian.setText(kembalian);
    }//GEN-LAST:event_tbPemesananMouseClicked

    private void cbPilihanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPilihanItemStateChanged
        dropdown();
    }//GEN-LAST:event_cbPilihanItemStateChanged
    private void tdata() {
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Kode");
        tb.addColumn("Nama");
        tb.addColumn("Harga");
        tb.addColumn("Jumlah");
        tb.addColumn("Total");
        tb.addColumn("Nominal");
        tb.addColumn("Kembalian");
        tbPemesanan.setModel(tb);
        try {
            java.sql.Connection conn = koneksiDB();
            String sql = "SELECT * FROM data_jual ";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                tb.addRow(new Object[]{
                    rs.getString("kode_item"),
                    rs.getString("nama_item"),
                    rs.getString("harga"),
                    rs.getString("jumlah"),
                    rs.getString("total"),
                    rs.getString("nominal"),
                    rs.getString("kembalian")
                });
                tbPemesanan.setModel(tb);
                tbRiwayat.setModel(tb);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void dropdown() {
        int sd = cbPilihan.getSelectedIndex();
        String harga = null, kode = null;
        switch (sd) {
            case 1:
                harga = "4000";
                kode = "1";
                break;
            case 2:
                harga = "3800";
                kode = "2";
                break;
            case 3:
                harga = "3500";
                kode = "3";
                break;
            case 4:
                harga = "1800";
                kode = "4";
                break;
        }
        lHarga.setText(harga);
        lKode.setText(kode);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jumlah;
    private javax.swing.JLabel Kembalian;
    private javax.swing.JLabel Nominal;
    private javax.swing.JButton bBayar;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bHitung;
    private javax.swing.JButton bKurang;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JLabel batas1;
    private javax.swing.JLabel batas2;
    private javax.swing.JLabel cash;
    private javax.swing.JComboBox<String> cbPilihan;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jtData;
    private javax.swing.JTextField lHarga;
    private javax.swing.JLabel lJumlah;
    private javax.swing.JTextField lKode;
    private javax.swing.JLabel lTotal;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel metodepembayaran;
    private javax.swing.JLabel nama_kasirnya;
    private javax.swing.JLabel namakasir;
    private javax.swing.JPanel pBar;
    private javax.swing.JPanel pFooter;
    private javax.swing.JPanel pInfo;
    private javax.swing.JPanel pInfo1;
    private javax.swing.JLabel tanggal;
    private javax.swing.JLabel tanggalnya;
    private javax.swing.JTable tbPemesanan;
    private javax.swing.JTable tbRiwayat;
    private javax.swing.JLabel total1;
    private javax.swing.JTextField uKembalian;
    private javax.swing.JTextField uNominal;
    // End of variables declaration//GEN-END:variables

}
